apiVersion: v1
kind: Service
metadata:
  name: beebsservice4
  labels:
    app: deploytest4
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: deploytest4
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: beebssite4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deploytest4
    spec:
      containers:
      - name: beebs
        image: thebeebs/howareyou:a13c9d65d1e6ebeb9e06d69921e40b236a59eea9
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
